### ISSUE TITLE
Local compile error

### ISSUE THREAD

**Issue by xz-cn** [AcalaNetwork/acala-dapp#100]
Trying to run the platform locally on a Mac, this error pops up after: `yarn run start`

![image](https://user-images.githubusercontent.com/46279370/81954146-13f0b380-963b-11ea-89e7-2ae6825f83fb.png)

It turns out the import of the svg files failed because of a mismatch of file names. In the `Token.tsx` file, the import used capital letters but the file names are actually lowercase. This happens for three file: `BTC.svg`, `DOT.svg`, `LDOT.svg`. It seems for some OS, this can result in a compile error.

5GCc7JDdXQ8QKnm8itDBd7hbKCKziS8eDrTTFeXmj6HhKTHk

**Comment by qwer951123** [comment]
thanks for your feedback, some problems with git and will be fixed in next commit.

**Comment by qwer951123** [comment]
fixed at #110
