### ISSUE TITLE
All The inputboxs allow negative numbers

### ISSUE THREAD

**Issue by JemmyXS** [AcalaNetwork/acala-dapp#101]
I found that negative number allowed in all the amount inputboxs, 
![image](https://user-images.githubusercontent.com/17928934/82109250-16e8c280-9767-11ea-9fc9-fc8c974d9126.png)

5EhmHo1EUTuCJueCYiFxPgj6uTSYAxgCPPKAs3LsiTURTsh8

**Comment by qwer951123** [comment]
When you input a negative, the input element will turn to error status, you can't submit extrinsic with negative numbers.
