### ISSUE TITLE
Withdraw Liquidity & Reward交易后界面没有reset可以超额取款

### ISSUE THREAD

**Issue by olddaddy2020** [AcalaNetwork/acala-dapp#102]
在Withdraw Liquidity & Reward中，提取完一笔存款后，界面没有恢复到初始状态，还是保留刚才的取款数额，实际上此时数额已超过了balance（图1），但是没有出现如图2那样正常状态下超额取款的红框警示，甚至仍可以点击withdraw进行交易，尽管这笔交易失败（Hash：0x58fe9faca2cf17a08f9c72a2853907af04c684a3b88cc790ae9c1ba3d16ac0ec）。

![图片](https://user-images.githubusercontent.com/61872737/82110345-2fa9a600-9770-11ea-9087-6227c06d3c70.png)

![图片](https://user-images.githubusercontent.com/61872737/82110359-4bad4780-9770-11ea-8a02-26aff45e9985.png)

5HY8hYMttrbm57MmN3o9p5ipF8i7eBjdWw7TQVsecoP7Uos6

**Comment by qwer951123** [comment]
Thanks for your feedback,  this will be fixed in next version.
