### ISSUE TITLE
交易记录地址错误的bug

### ISSUE THREAD

**Issue by lijiahao666** [AcalaNetwork/acala-dapp#104]
当我在向波卡网络的钱包地址转账时，我发现转账后的交易记录地址与目标地址不一样。
![cffb37703796d80e2f2faa45e185c58](https://user-images.githubusercontent.com/57653984/82142630-5949f680-9870-11ea-8ba4-c025a52f48b6.png)
![438724fd7cc4a99e5eb496d9d04f70a](https://user-images.githubusercontent.com/57653984/82142674-a0d08280-9870-11ea-92e1-531f206afc26.png)
![5ecacc274bf796888f82ad5139cd33a](https://user-images.githubusercontent.com/57653984/82142680-a6c66380-9870-11ea-93c2-71bd2456d6b4.png)
地址：5CG4jmkk1neZzbKCeQg7kYv9PMko8zkcRqVvAFzPHuBD673q

**Comment by qwer951123** [comment]
Thanks for your feedback, the two addresses are the same but in a different format. in our current chain, all addresses will be formatted with prefix 5. if you are using the mobile app, you can change the network to acala test-net.
