### ISSUE TITLE
部分DOT铸造LDOT借贷aUSD后，剩下的DOT没法铸造，按钮灰色没法点击

### ISSUE THREAD

**Issue by nantianhaike** [AcalaNetwork/acala-dapp#108]
部分DOT铸造LDOT并借贷aUSD，如图显示：
![image](https://user-images.githubusercontent.com/35984173/82288244-a3e48380-99d4-11ea-81fb-8510dcc3e39d.png)

剩下的LDOT如图显示：
![image](https://user-images.githubusercontent.com/35984173/82288284-bced3480-99d4-11ea-8bdf-a527ab6f9d8b.png)

剩下的LDOT没法借贷，按钮灰色，无法点击，如图显示：
![image](https://user-images.githubusercontent.com/35984173/82288330-d3938b80-99d4-11ea-9a43-c03ad69dd0d2.png)

My Acala Address：5EEub2a54XhN97vkd41zKzbooqadfatnx5VEmHkvvFP8hj3T

**Comment by qwer951123** [comment]
Thanks for your feedback, because you already have an LDOT loan, you can manager your debit and collateral in it, no necessary to create a new one.

**Comment by nantianhaike** [comment]
关键是剩下的LDOT没法被用来借贷aUSD了，这设计应该是不合理的

**Comment by nantianhaike** [comment]
只有全部取回了之前的LDOT，重新创建一个新的LDOT借贷,，剩下的LDOT才可以使用得上

**Comment by qwer951123** [comment]
> 关键是剩下的LDOT没法被用来借贷aUSD了，这设计应该是不合理的

剩下的 LDOT 在 manager 里面可以继续抵押的
<img width="1374" alt="截屏2020-05-19 下午2 30 54" src="https://user-images.githubusercontent.com/4833280/82292360-5c162a00-99dd-11ea-8179-8576eba4cbb2.png">
截图中 deposit 这个按钮就可以继续抵押 LDOT
