### ISSUE TITLE
error in writing the number

### ISSUE THREAD

**Issue by randlmac** [AcalaNetwork/acala-dapp#112]
Self Servised Loan tab,System info, Ausd in Supply : 1,18,47,125.134887
I think there is error in writing, too many commas, that can mislead users of the platform
![777](https://user-images.githubusercontent.com/55245481/82403852-8103af00-9a68-11ea-9f16-179f8d5af37c.png)
5DCdUUZSEsdB3JBwdyQsKjEwdjWLyVajJaeki66M5YhGYWyK

**Comment by qwer951123** [comment]
Thanks for your feedback, fixed at #113
