### ISSUE TITLE
通过其它账号Transfer过来的dot在进行借贷、swap、以及铸造LDOT都显示失败，可以反复复现

### ISSUE THREAD

**Issue by nantianhaike** [AcalaNetwork/acala-dapp#114]
如下图所示，通过其它账号给此账号转账了1.9个DOT过来
![image](https://user-images.githubusercontent.com/35984173/82427207-58f16b80-9abb-11ea-9372-065af0a92693.png)

利用已有的1.9个dot 进行借贷的时候，显示失败，如下图所示：
![image](https://user-images.githubusercontent.com/35984173/82427410-a968c900-9abb-11ea-8738-40df21f64139.png)

利用已有的DOT进行swap操作时，也提示失败，如下图所示：
![image](https://user-images.githubusercontent.com/35984173/82427548-d5844a00-9abb-11ea-81b7-e7c5b95f544e.png)

利用已有的dot进行铸造LDOT时，也提示出错，如下图所示：
![image](https://user-images.githubusercontent.com/35984173/82427660-f77dcc80-9abb-11ea-96f1-b01819427299.png)

而且只要是通过其它账号转账过来的dot，都会出现上面的问题，百分百可以复现。
通过水龙头领取的DOT则不会出现这样的问题。
**做测试的时候先注册一个新的钱包，再通过其它账号给这个刚注册的账号转账DOT，则上面的问题百分百可以复现。**

Acala address：5CB6bxLb9jDna7tAeJMAMRaFDsSjRhiEvwFJJpRDCLXBE55o

**Comment by qwer951123** [comment]
谢谢反馈，我注意到你的新账号没有 ACA，你可以转一些 ACA 到你的账号里，因为发送交易需要一些 ACA 作为手续费，如果没有 ACA 就会导致交易失败。

**Comment by nantianhaike** [comment]
应该是没有ACA的原因
