### ISSUE TITLE
在进行Self Serviced Loan操作时，Deposit 多少数量的LDOT, Generate 多少数量的 aUSD会显示具体的数量，但是过些时候来看就变成含糊不清的some 了

### ISSUE THREAD

**Issue by nantianhaike** [AcalaNetwork/acala-dapp#116]
在进行Self Serviced Loan操作时，Deposit  10 LDOT, Generate 230个 aUSD，下面操作记录里面会显示具体的数量，如下图所示：
![image](https://user-images.githubusercontent.com/35984173/82530666-6ae11600-9b70-11ea-8e3a-bafc1e4725be.png)

但是过一些时间再打开看操作记录时，这些具体的数字被模糊不清的some所代替，用户想要知道之前的实际借贷情况时变得没有可能，如下图所示：
![image](https://user-images.githubusercontent.com/35984173/82530794-ac71c100-9b70-11ea-83ce-6c6ff5ec478c.png)

Acala address：5CB6bxLb9jDna7tAeJMAMRaFDsSjRhiEvwFJJpRDCLXBE55o

**Comment by qwer951123** [comment]
感谢反馈，some 是因为从链上没有读取到交易发生时的 exchangeRatio 导致的。读取到历史记录只有 debits 值，需要从链上读取 exchangeRatio 换算成相应的 aUSD 值，由于读取失败，所以显示 some 来代替。我们正在开发历史记录的接口，让历史记录独立于链数据。
