### ISSUE TITLE
Can not open https://apps.acala.network/

### ISSUE THREAD

**Issue by atinst** [AcalaNetwork/acala-dapp#118]
![Snipaste_2020-05-23_01-27-57](https://user-images.githubusercontent.com/32417799/82693808-c1e00b80-9c94-11ea-8629-aa4fe104e6e3.png)

My network is normal, but I can't open it https://apps.acala.network/ 。 This kind of problem is terrible. It makes me feel that your platform is very unstable.

**Comment by atinst** [comment]
Acala:`5HnJRCcbFaTjaYhmhTiNavSStkxRAmeX2EiEJq2vSnN5Q4TJ`

**Comment by qwer951123** [comment]
Thanks for your feedback, the default node which the dapp used had some problem and it is work now.
