### ISSUE TITLE
未知原因导致的链上操作无法执行

### ISSUE THREAD

**Issue by lijiahao666** [AcalaNetwork/acala-dapp#120]
未知原因导致的链上操作无法执行，包括闪兑，借贷和铸造LDOT。由于无法发送视频，我制作了一个gif。
![20200524_123230](https://user-images.githubusercontent.com/57653984/82746254-5004e080-9dc0-11ea-991d-a1fea984e8b1.gif)

5CG4jmkk1neZzbKCeQg7kYv9PMko8zkcRqVvAFzPHuBD673q

**Comment by qwer951123** [comment]
谢谢反馈，前几天连接点节点网络不好，经常出问题，这几天换了节点应该会好一点。
