### ISSUE TITLE
Deposit!

### ISSUE THREAD

**Issue by MarininM** [AcalaNetwork/acala-dapp#121]
![IMG_7981](https://user-images.githubusercontent.com/65186627/82933525-b0e41280-9f92-11ea-8867-1779dbaab1d7.jpg)
We  can see information about deposit DOT but we don’t see information about conditions of deposit .
I don’t understand which I am making deposit.
Would be great if you can show deposit conditions in one line.
Owner of DOT will be able to immediately see benefits of the deposit)))))

5FF7F1eDV59gH1yzamUuhzWkjwf96gZDWDK7tCUDehDuKfQk

**Comment by qwer951123** [comment]
THX, the benefits of the deposit according to your deposit amount and will display in the estimated Profit /Era line. There is no condition of deposit beside that you should be owned some DOT

**Comment by MarininM** [comment]
Cool! fine! I'm glad that these bug will be taken into Liquid DOT!
