### ISSUE TITLE
Homa (Liquid DOT Redeem) - should display DOT instead of LDOT

### ISSUE THREAD

**Issue by mil99** [AcalaNetwork/acala-dapp#123]
Current: When user enters x LDOT to redeem, UI is displaying what the user has keyed in, which makes no sense. User has to manually calculate the expected amount of DOT to receive.

Expected: UI should display the expected amount of DOT to receive (after deducting claim fees), and not LDOT.

![UIbug2](https://user-images.githubusercontent.com/66069419/83276059-a6c84b00-a202-11ea-94cb-b4bd441f6417.jpg)

5F3rYPmFB53XttPd8Zq9QqPxMFDUuVqDx4zjVjmqy6n4Ve4M

**Comment by qwer951123** [comment]
The received amount of DOT is more useful for users and we can display an estimated DOT amount, THX.
