### ISSUE TITLE
Negative numbers as input

### ISSUE THREAD

**Issue by xz-cn** [AcalaNetwork/acala-dapp#145]
I think in all cases, negative number input should be made impossible in the front-end form design. 
![image](https://user-images.githubusercontent.com/46279370/88539092-2b88e700-d043-11ea-810d-bdb06ae22072.png)
![image](https://user-images.githubusercontent.com/46279370/88539097-2e83d780-d043-11ea-8819-beac34d63909.png)

5GMvp5okVesv3JHxNA21SeFbXtMMtwy6EmPvtN5HpHLUuRCy

**Comment by qwer951123** [comment]
ale
