### ISSUE TITLE
No yesterday's history in Save&Earn page

### ISSUE THREAD

**Issue by vincentlyl** [AcalaNetwork/acala-dapp#148]
I deposited yesterday and withdraw today. There is only the withdraw record as attached.
![8371595858761_ pic](https://user-images.githubusercontent.com/9255120/88551389-6562e900-d055-11ea-8054-dad629396aed.jpg)

my Acala mandala address is 5Gc9V1K6kV74uXWKn6cteygm2Zy85pYfHxfZdfFvEcPcyYyX

**Comment by qwer951123** [comment]
Welcome commit issues to [polkawallet](https://github.com/polkawallet-io/polkawallet-flutter/issues), this will be closed.
