### ISSUE TITLE
Acala操作平台网页版突然打不开了

### ISSUE THREAD

**Issue by ottomu1314** [AcalaNetwork/acala-dapp#155]
今天准备从Acala网页版操作平台跨链转账aUSD到Laminar操作平台，前者直接无法打开页面（已检查不是电脑和网速问题），转圈提示后直接一片空白，后者Laminar网页则不存在任何问题。这是今天才出现的状况，昨天是正常的。请知悉。
5E7b8rmiWDahDN6ZUNuyqmSirQsPj8PAMZ9CYMaURCjcDEqn

**Comment by qwer951123** [comment]
目前 firfox 有时候会连不上节点，我们正在检查节点服务，如有可能的话可以使用 chrome 浏览器
