### ISSUE TITLE
Issue with polkadot{.js} extension in Brave browser

### ISSUE THREAD

**Issue by vimm007** [AcalaNetwork/acala-dapp#157]
In Brave browser https://apps.acala.network/ doesn't work with polkadot{.js} extension. Extension inslalled.
![image](https://user-images.githubusercontent.com/68907663/88667321-e1a70c00-d0e9-11ea-92fd-224d7808b919.png)

5CqphTautn3mnQaNYzG5G4MHv3SL5imggeLasnMvtb8oQ8fx

**Comment by ltfschoen** [comment]
**My Acala Mandala Address: 5F2QSwPHobet1pLFTEw6mkcT8bwZdEMmHfBGYPkiK7Pgxdex**

I've been using the latest Brave browser using the latest Polkadot.js Extension and I haven't encountered that issue.

Did you authorize Polkadot.js Extension to interact with the dapp?

**Comment by qwer951123** [comment]
I had tried the latest Brave browser but success, maybe you rejected acala-dapp use polkadot.js.
<img width="504" alt="Screen Shot 2020-07-30 at 4 39 26 PM" src="https://user-images.githubusercontent.com/4833280/88901318-3d58cd00-d283-11ea-9ed9-504cfc1cd403.png">.
would you like to disable polkadot.js extension and then reopen it.
<img width="459" alt="Screen Shot 2020-07-30 at 4 41 07 PM" src="https://user-images.githubusercontent.com/4833280/88901519-7a24c400-d283-11ea-93ad-afb83ec49c26.png">

**Comment by vimm007** [comment]
Hm, strange. Works as expected today.
