### ISSUE TITLE
Missing DOTs following LDOT 'Mint & Stake'.

### ISSUE THREAD

**Issue by romanuz** [AcalaNetwork/acala-dapp#161]
On 2020/07/27 10:03, I tried 'Mint & Stake' with 0.94 DOT (which should have resulted in about 9.4 LDOT).
Transaction is here:
https://acala-testnet.subscan.io/extrinsic/0xa6d6612d59d55b2fdc407d79ea7320428fab0d00cd9ceab23e2fef739fd09a53

Then on 2020/07/27 10:46 I minted & staked another 0.65 DOT (which resulted in about 6.5 LDOT).
Transaction is here:
https://acala-testnet.subscan.io/extrinsic/0x5f46431dd92c2e39f45a1391e03715534c5feaf1d0bd0bcf95d7a2f4bc2ff059

About 12 hours later I decided to redeem, but Redeem/Unstake balance was showing only 6.45 LDOTs (not sign of the first balance transaction of 0.94 DOT / 9.4 DOT).

Image is attached - it shows history of transactions and there were no moves out of 0.94 DOT / 9.4 LDOT.

![Liquid DOT - Missing LDOTs - Balance NOT updated](https://user-images.githubusercontent.com/68799740/88850031-c35c1180-d1b8-11ea-91d2-c2a35c94828a.PNG)

**Comment by romanuz** [comment]
My address:  5FYp3sLahQayxvorwEfNUBpU1uZvU6uvSoYw3qmeipwzBbot
Also seen in transactions' subscans above.

**Comment by qwer951123** [comment]
Hi, I verified your TX history and find an open LDOT Loan [ACTION](https://acala-testnet.subscan.io/extrinsic/0x882697a620574521f827f98dec115a9763e177118ab04fc62b7bef8c98e9423c) before redeeming. maybe this is the reason why only showed 6.45 LDOTs.

**Comment by romanuz** [comment]
I'll try to clarify it a bit more - I used 'Mint & Stake' 2 times.

The 1st mint (no redeem):
https://acala-testnet.subscan.io/extrinsic/0xa6d6612d59d55b2fdc407d79ea7320428fab0d00cd9ceab23e2fef739fd09a53

Some loan activity.

The 2nd mint and redeem are:
https://acala-testnet.subscan.io/extrinsic/0x5f46431dd92c2e39f45a1391e03715534c5feaf1d0bd0bcf95d7a2f4bc2ff059
https://acala-testnet.subscan.io/extrinsic/0xc507b21ec00b4b233315f170dd8edfef27da46af7dc67f234e35165103b69fb3


It is in the 2nd redeem that staked 0.94 + 0.65 DOTs should have been shown (together) in the UNSTAKE panel - but it only
showed 0.65 DOTs. I couldn't unstake 0.94 DOTs because they weren't shown.

**Comment by romanuz** [comment]
I changed the subject to reflect more objectively missing DOTs in staked DOT balance in 'Mint & Stake'.

**Comment by qwer951123** [comment]
I know what you mean.  we calculate the DOT amount which you staked base on the LDOT amount, LDOT is the share of the staking pool, so If you change LDOT amount like transferring to other, depositing to the loan, your staked DOT amount will change.
