### ISSUE TITLE
Block Undefined Error 

### ISSUE THREAD

**Issue by Crypto-Guru** [AcalaNetwork/acala-dapp#163]
I did a payback transaction of aUSD and noticed the block state struck in Unfinalized state even after 10 mins. 
Block# 499775.
When I checked in https://acala-testnet.subscan.io/extrinsic/ for this block, I see aUSD amount being reflected in events. 
However, after few seconds, the GUI refreshes and shows it as Block Invalid.
I am attaching 2 screenshots: 1 that contains transaction details, other with invalid block. I have recorded the behaviour in case if you want to more details.
<img width="1679" alt="Acala-Transaction" src="https://user-images.githubusercontent.com/68987219/88892983-4df94b00-d263-11ea-9824-5e166a7094d3.png">
<img width="1680" alt="Acala-Block-Undefined" src="https://user-images.githubusercontent.com/68987219/88892999-53569580-d263-11ea-965d-bcc19e35107a.png">

**Comment by Crypto-Guru** [comment]
My Acala address: 5DfNVfJTgpspTA4bz7w1DNJmf4eAEcCZ76AktJonPXUPwR6U

**Comment by qwer951123** [comment]
seem that subscan has some trouble with this block, check out [acala console](https://console.acala.network/#/explorer), the highest finalized block is 576,682 now.

**Comment by Crypto-Guru** [comment]
ok if  that is a subscan issue, flag this to that team.
