### ISSUE TITLE
Laminar dashboard. The numbers are displayed incorrect . Windows, 1920x1080, Chrome:

### ISSUE THREAD

**Issue by Ryabina-io** [AcalaNetwork/acala-dapp#173]
![image](https://user-images.githubusercontent.com/67865446/88968501-1963ae80-d2b8-11ea-81b1-bece2b7e2cae.png)
5FEoLBq9BP8X3iU6iPmW2KWJahcCazeSaLPd2CamVfdwsCc1

**Comment by xlc** [comment]
Please report laminar UI issues at https://github.com/laminar-protocol/flow-exchange/issues
This is a known issue and I will close it here for new. Thanks for reporting.
