### ISSUE TITLE
Cannot deposit liquidity

### ISSUE THREAD

**Issue by hatred09** [AcalaNetwork/acala-dapp#174]
Cannot deposit liquidity for ACA pool. Has been this way for the past one hour . error showing even if I have the sufficient amount of aca token for deposit . simply wasting transaction cost for error like insufficient balance in the deposit for liqidity
![w](https://user-images.githubusercontent.com/41484322/88978354-28a92300-d2dd-11ea-9ae9-26a3f1c84009.png)

![error](https://user-images.githubusercontent.com/41484322/88976384-93585f80-d2d9-11ea-93ba-418146fb2167.png)
5FsGNbmaQocxdioLbUzFfR5vYChtJGdmftVCenv1QXawEgvu

**Comment by qwer951123** [comment]
Seems like you deposit all your ACA to the liquidity pool, you should remain some ACA for the tx fee.

**Comment by hatred09** [comment]
yes, i tried it with this way and it worked. Still I think they should show the tx fee while depositing to be clear.

**Comment by qwer951123** [comment]
> yes, i tried it with this way and it worked. Still I think they should show the tx fee while depositing to be clear.

Yeah, We are designing tx fee check and display in each subsystem now.

**Comment by hatred09** [comment]
Good, hope it comes out soon.
