### ISSUE TITLE
wallet中莫名出现2.84945 renBTC

### ISSUE THREAD

**Issue by comeonon** [AcalaNetwork/acala-dapp#177]
在Self Serviced Loan中将renBTC全部抵押，交易成功的同时，钱包中会莫名出现2.84945 renBTC（本应为0），尝试swap中用renBTC进行兑换时，显示balance is too low。当在Self Serviced Loan中把抵押的renBTC赎回后，钱包显示了正常数额，那个突然出现得到2.84945 个renBTC消失了。但是只要把renBTC再次全部抵押，2.84945个renBTC又会神奇的出现在钱包中。

下图是抵押全部renBTC，0x6b0ab9bc7bcfd3d1e8ad24158dd410e96001721a637332bf12bd0a30d1e498ca
![image](https://user-images.githubusercontent.com/69046774/89047189-a96d2b00-d380-11ea-8c94-0070bc9ced1a.png)

下图是钱包中莫名出现的renBTC
![image](https://user-images.githubusercontent.com/69046774/89047683-5051c700-d381-11ea-87fb-a3257445726b.png)

下图是赎回抵押的renBTC后（0x634515cdd68edc7aef568f7560adde155126010aac7a064343e2973c9efc5983），钱包正常显示

![image](https://user-images.githubusercontent.com/69046774/89047860-9ad34380-d381-11ea-9830-7347a8d7ecf8.png)

下图是再次抵押后（0xd494b01c14db6596185c85d3b4c37f7d37fde45dc5a8ba0f3e33f6a8927063f2）后，钱包里的2.84945个renBTC再次出现
![image](https://user-images.githubusercontent.com/69046774/89048116-f3a2dc00-d381-11ea-897b-07e8900a3871.png)

5CcTrXNHdJUYttyDNsQFDdWMcBPY8YvZF8x6WMXVapYQ644p

**Comment by qwer951123** [comment]
Thanks for your feedback, this is a number display bug.
