### ISSUE TITLE
renBTC issue

### ISSUE THREAD

**Issue by luckyve** [AcalaNetwork/acala-dapp#178]
![1a](https://user-images.githubusercontent.com/58464914/89052429-f8519b00-d355-11ea-8c79-2b65fbc0030e.png)
![2](https://user-images.githubusercontent.com/58464914/89052433-f982c800-d355-11ea-9bfc-d7020091ebbe.png)

address:
5GQuKzAMK46khha8Fa5bKk44hmkafhtFnDLXCjGoQPnW36u6

**Comment by qwer951123** [comment]
Thanks for your feedback, This is a demo page, we will expedite to complete RenVM cross-chain feature.
