### ISSUE TITLE
aUSD Usage

### ISSUE THREAD

**Issue by intutkri2** [AcalaNetwork/acala-dapp#180]
Margin Trading Menu in the Acala Mandala App for carrying out one of the three meaningful tasks for the Manadala Festival Season 3 Week 1 - Transfer aUSD to Laminar Chain, and use it _**either for synthetic asset, or margin trading**_ not found 

Acala Mandala App wallet  :5DegibRmPCeEbxSqmpj9ZrrcEnMHbRc8zuJS91hG7z4k9qba

**Comment by qwer951123** [comment]
you can do synthetic asset and margin trading in  (flow-laminar)[https://flow.laminar.one/dashboard]
