### ISSUE TITLE
Cross Chain Ren-BTC: Edit of Mint amount is disabled.

### ISSUE THREAD

**Issue by Crypto-Guru** [AcalaNetwork/acala-dapp#181]
During Minting of Ren-BTC amount, if we close the "Deposit BTC" window to edit the amount to be minted, the option to edit the BTC amount is disabled. We need to click on "Previous" button and re-enter the amount instead of editing the amount. 
It seems there is no edit option for BTC amount. 
Attaching the screenshots for reference.
Screen 1 - Entering the amount
Screen 2 - Confirming the amount
Screen 3 - Closing the Deposit BTC screen 
Screen 4 - Trying to Edit the amount after closing 'Deposit BTC' screen
Screen 5 - Going back to Previous screen with the intent to edit the amount but surprised to see the amount being cleared.

<img width="1367" alt="Screen-1" src="https://user-images.githubusercontent.com/68987219/89102063-454f7300-d423-11ea-8901-8d3ecd44b317.png">
<img width="1369" alt="Screen-2" src="https://user-images.githubusercontent.com/68987219/89102067-526c6200-d423-11ea-93ce-0660ba558681.png">
<img width="1367" alt="Screen-3" src="https://user-images.githubusercontent.com/68987219/89102076-5dbf8d80-d423-11ea-9846-84db32470308.png">
<img width="1368" alt="Screen-4" src="https://user-images.githubusercontent.com/68987219/89102079-6617c880-d423-11ea-9152-4d3ffc32be53.png">
<img width="1368" alt="Screen-5" src="https://user-images.githubusercontent.com/68987219/89102081-6c0da980-d423-11ea-8006-087a7d05ec32.png">

My Acala address is: 5DfNVfJTgpspTA4bz7w1DNJmf4eAEcCZ76AktJonPXUPwR6U

**Comment by qwer951123** [comment]
Thanks for your feedback, This is a demo page, we will expedite to complete RenVM cross-chain feature.
