### ISSUE TITLE
借贷遭清算？没有任何痕迹？

### ISSUE THREAD

**Issue by helpu2020** [AcalaNetwork/acala-dapp#183]
昨天抵押0.0899个renBTC，借出了900aUSD （0xefdc0b4e4c7b2bdd182d0e4f2bb0e05a56dd5892b8719127f79b97b5c8b88655），刚才发现在Overview中已没有这笔借贷。这应该是今天BTC价格剧烈波动遭自动清算了，但是没有找到任何痕迹（包括时间、清算价格，还结余多少等等），没有历史记录，在subscan上也没查到相关交易记录？

![image](https://user-images.githubusercontent.com/69102218/89117520-eba58200-d4d0-11ea-8c9e-c225e2176789.png)

![image](https://user-images.githubusercontent.com/69102218/89117551-27d8e280-d4d1-11ea-8a93-9eca51b42db9.png)

5DXtkdNzuUoS9DSF9xD7cvk7pwBDNfLT9QX84H5CwaGJj7H8

**Comment by xlc** [comment]
是被清算了，subscan可以看到所有的清算不过目前无法根据账号查询，UI暂时也没有支持显示，我们会完善
https://acala-testnet.subscan.io/extrinsic?module=cdpengine&call=liquidate&signedChecked=all

**Comment by qwer951123** [comment]
Duplicate of #103
