### ISSUE TITLE
抵押dot进行借贷的操作被连续执行了两次

### ISSUE THREAD

**Issue by hijonehi** [AcalaNetwork/acala-dapp#184]
Self Serviced Loan时进行抵押1dot借出111aUSD的操作，发现连续执行了两次 （0x39200c5a71aac577df7081983a4ed9ea23bc9648aa58720b530137280249b92c，0xc1e6082e39b6fe6cbed064a4a1a5d737c390dc3debb594a0f7c116e4b3cd5ba9）。正常情况下，应该是必须偿还了上一次借贷，才能再次进行同一个币种的借贷操作。

![image](https://user-images.githubusercontent.com/61875854/89120469-24515580-d4e9-11ea-83ae-efc3cddc0304.png)

5FcKCJ2K86MsKXB58wvk7zXz5XYENC3s9bp5jDfoH3PNimvh

**Comment by qwer951123** [comment]
在系统里面，你可以对你的同一种币种的债仓做任意次 **借贷/还款/抵押/提取** 操作，只需要确保操作后抵押率高于最低抵押率或者清算抵押率，防止债仓被清算。

**Comment by hijonehi** [comment]
> 在系统里面，你可以对你的同一种币种的债仓做任意次 **借贷/还款/抵押/提取** 操作，只需要确保操作后抵押率高于最低抵押率或者清算抵押率，防止债仓被清算。

你说的这个系统是不允许的。比如借贷了一笔dot，当试图再次借贷dot时，选择的按钮是灰色的，鼠标变成一个红圈叉，见下图：
![image](https://user-images.githubusercontent.com/61875854/89312737-2f071880-d6aa-11ea-9c88-e139227e3ee0.png)

**Comment by qwer951123** [comment]
> > 在系统里面，你可以对你的同一种币种的债仓做任意次 **借贷/还款/抵押/提取** 操作，只需要确保操作后抵押率高于最低抵押率或者清算抵押率，防止债仓被清算。
> 
> @qwer951123 qwer951123 你说的这个系统是不允许的。比如借贷了一笔dot，当试图再次借贷dot时，选择的按钮是灰色的，鼠标变成一个红圈叉，见下图：
> ![image](https://user-images.githubusercontent.com/61875854/89312737-2f071880-d6aa-11ea-9c88-e139227e3ee0.png)
> 
> 所以，前两天我发现借贷连续被执行了两次，我觉得是不正常的。现在问题来了，你们系统设计的到底是同一币种可以连续借贷，还是必须先偿还再借贷？

系统设计上是容许同种币种连续借贷的，这里的禁止只是针对创建流程，创建流程里面的一些参数的计算默认认为用户没有该币种的债仓。
