### ISSUE TITLE
laminar中margin trading首页可以显示My Positions / Orders交易记录，但是进入具体交易对页面My Positions / Orders Open显示没有数据

### ISSUE THREAD

**Issue by frighter518** [AcalaNetwork/acala-dapp#199]
laminar中margin trading首页可以显示My Positions / Orders交易记录，但是进入具体交易对页面My Positions / Orders Open显示没有数据
5CccLc64WB2hwWorqg92A4S5y9fwAiAdbAKLRY5obDskA26N

**Comment by xlc** [comment]
Laminar 的问题请发送到 https://github.com/laminar-protocol/flow-exchange/issues

https://flow.laminar.one/margin/2/EURUSD 可以看到交易数据，不同池子是不一样的。

**Comment by frighter518** [comment]
下级页面我一点，进的是https://flow.laminar.one/margin/0/EURUSD这个页面，看不到交易数据




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiliang Chen"<notifications@github.com&gt;; 
发送时间: 2020年8月4日(星期二) 上午10:58
收件人: "AcalaNetwork/acala-dapp"<acala-dapp@noreply.github.com&gt;; 
抄送: "36777145"<36777145@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AcalaNetwork/acala-dapp] laminar中margin trading首页可以显示My Positions / Orders交易记录，但是进入具体交易对页面My Positions / Orders Open显示没有数据 (#199)





 
Laminar 的问题请发送到 https://github.com/laminar-protocol/flow-exchange/issues
 
https://flow.laminar.one/margin/2/EURUSD 可以看到交易数据，不同池子是不一样的。
