### ISSUE TITLE
Sign the transaction pop up window

### ISSUE THREAD

**Issue by whoissatoshi** [AcalaNetwork/acala-dapp#200]
1. Login
2. Go to **Wallet tab** (1st tab)
3. Click any **Transfer** button 
4. Transfer pop up window is appeared.
5. Fill **Account** and **Amount** fields and click **Confirm** button 
6. Sign the transaction pop up appeared.
7. Close this pop up window (close X CTA on the top right corner ).
8. Close **Transfer** pop up (close X CTA on the top right corner ).
9. Go to **Swap** tab and back to **Wallet**
10. Click any **Transfer** button, Transfer pop up window is appeared
11.  Fill **Account** and **Amount** fields and click **Confirm** button.
12.  Sign the transaction pop up appeared.
13. Fill password field and click **Sign the transaction** button

EX: process is finished
AR: 2 more Sign the transaction pop up windows appeared
![Selection_019](https://user-images.githubusercontent.com/69153826/89276751-b160ef80-d64c-11ea-9fd7-9767462b3252.png)

5F2FNhhVeG9bW4tP5te4a7asBJvSHQg31RzkoETLpUN161gV

**Comment by qwer951123** [comment]
It seems like polkadot.js extension caused this issue, and already fixed.
