### ISSUE TITLE
ClaimFee is 0

### ISSUE THREAD

**Issue by whoissatoshi** [AcalaNetwork/acala-dapp#207]
1. Login.
2. Go to **Liquid DOT** tab --> **Advanced**.
3. Choose **Redeem & Wait for Unbounding Period**
4. Fill LDOT field.

ER: ClaimFee is not 0.
AR: ClaimFee is 0

P.S. you can add **MAX** option for LDOT field

5F2FNhhVeG9bW4tP5te4a7asBJvSHQg31RzkoETLpUN161gV

![Selection_025](https://user-images.githubusercontent.com/69153826/89310080-e71dcc80-d67c-11ea-8c04-95acdbf68169.png)

**Comment by qwer951123** [comment]
The claim fee is 0 when you chose this way to redeem your LDOT, we charge a step-wise claim fee according to your waiting time, the longer you wait the less the claim fee will be charged until to 0
