### ISSUE TITLE
Redeem Tracker displays only first 6 record

### ISSUE THREAD

**Issue by whoissatoshi** [AcalaNetwork/acala-dapp#208]
1. Login.
2. Go to **Liqud DOT** tab --> **Advanced** --> **Redeem**.
3. Select **Redeem in ERA**. Choose any ERA.
4. Fill the LDOT field, click Redeem and sign tx.
5. Repeat 3-4 steps 7 times.

Actual result: **Redeem Tracker** shows only first 6 records
Expected result: **Redeem Tracker** shows all record. Please take a look **Transaction** section. 1st and 2nd rows are not displayed in **Redeem Tracker** section.

P.S. **Transaction** section displays only last 5 tx. Please add some paging.
 
5F2FNhhVeG9bW4tP5te4a7asBJvSHQg31RzkoETLpUN161gV

![Selection_026](https://user-images.githubusercontent.com/69153826/89311827-2b11d100-d67f-11ea-8016-5d8599c7230b.png)

**Comment by qwer951123** [comment]
we will merge redeem amounts in same ERA, so 1st and 2nd transactions merged to ERA 28, and displayed in Redeem Tracker.
