### ISSUE TITLE
Incorrect reward ratios in Deposit & Earn section

### ISSUE THREAD

**Issue by Mitra8** [AcalaNetwork/acala-dapp#209]
Based on the implied fees for swap transactions, it seems that the actual reward ratios are less than those presented in Deposit & Earn section (by a fraction of 10). So, for example, renBTC+aUSD shows 4.09%, however the actual rate is probably 0.409%.
![image](https://user-images.githubusercontent.com/69203809/89312714-3f0a0280-d680-11ea-9b76-b46eaa87e44f.png)

5H985QyVoRZudfw2p6DvmwhdfYob8LkgK4pCZdf9rnioUZUd

**Comment by xlc** [comment]
The reward ratio is not swap fee. It is additional rewards for lp. Even no one doing swap lp will still getting this reward.
