### ISSUE TITLE
还款失败Bug

### ISSUE THREAD

**Issue by Jason1215** [AcalaNetwork/acala-dapp#211]
![image](https://user-images.githubusercontent.com/26864300/89369413-9fe11b80-d710-11ea-9bc4-529b5ab5edd1.png)

5Ff71anXLiNKQxXGRLmxTTajjhWDeiUy492p3MMChZB6Udkj

**Comment by qwer951123** [comment]
Thanks for your feedback, Pls. submit the issue to [polkawallet](https://github.com/polkawallet-io/polkawallet-flutter).
