### ISSUE TITLE
polkawallet does not show the position

### ISSUE THREAD

**Issue by jiangzhanwei** [AcalaNetwork/acala-dapp#226]
system: mi9
wallet: polkawallet V0.8.6
When I conducted leveraged trading in polkawallet, after the transaction was successful, I did not display the position information and could not close the position. However, the margin balance showed a change
![WechatIMG6](https://user-images.githubusercontent.com/19163404/89702604-6b21ce00-d975-11ea-8aa4-7be9199e3da4.jpeg)

my dot address: 
14B7G8NRMt2YuV6n3TKf2wyiGSew1wwdVjEEvWwqdDbKa7aZ
my acala address:
5FEp7o7MW6m5Tx6G5pGeto9ZQpfHKePVREVkmDxV58ZoPg6H

**Comment by qwer951123** [comment]
Thanks for your feedback, you can report this issue to [polkadot-wallet](https://github.com/polkawallet-io/polkawallet-flutter)
