### ISSUE TITLE
Transaction History遗漏记录

### ISSUE THREAD

**Issue by olddaddy2020** [AcalaNetwork/acala-dapp#23]
谷歌浏览器
http://apps.acala.network/#/loan
使用self serviced loan进行操作后，当账户退出后再进入时，Transaction History显示记录不全，只剩最后一条loan记录（https://polkascan.io/pre/acala-mandala/extrinsic/0x652151495987ab834aac403bf21f81a229ea231d24ddcb939459200d0d96226e）

5GR5ZkscxFJHRroPDPG6TxZ28xGJBnsrYXJCR9nbmiuWWEDR

**Comment by qwer951123** [comment]
目前所有的历史记录都是存在本地的，可能会由于切换账号操作被覆盖掉，我们计划使用第三方的数据服务，实时的从链上读取操作历史。

**Comment by qwer951123** [comment]
track this issue at #36 and this will be closed.
