### ISSUE TITLE
拍卖成功的交易只能在subscan查，app上怎么不做一个，不做不利于后期提升拍卖的参与度。

### ISSUE THREAD

**Issue by frighter518** [AcalaNetwork/acala-dapp#236]
拍卖成功的交易只能在subscan查，app上怎么不做一个，不做不利于后期提升拍卖的参与度。
5CccLc64WB2hwWorqg92A4S5y9fwAiAdbAKLRY5obDskA26N

**Comment by qwer951123** [comment]
目前这方面的产品还在规划中。
