### ISSUE TITLE
Polkadot{.js}扩展程序 ，只显示当前6个账户。不能下拉

### ISSUE THREAD

**Issue by yidianshui** [AcalaNetwork/acala-dapp#243]
Polkadot{.js}扩展程序 ，只显示当前6个账户。如果创建了更多的账户，不能下拉，创建了更多的账户，下面的那些账户。不能操作。
![22](https://user-images.githubusercontent.com/36132527/90310912-8d44be80-df28-11ea-8338-532509472e0e.png)
![111](https://user-images.githubusercontent.com/36132527/90310920-959cf980-df28-11ea-84bb-6faabbcdaccb.png)

5EnWSikTvi8Y3S6vQ8TM3q5joFe8pCa4LjAbmEaXywwE6ioG

**Comment by jiangfuyao** [comment]
I've tested that it can slide.

**Comment by qwer951123** [comment]
It seems like Polkadot{.js} 's issue, you can report this issue to [Polkadot{.js} repo](https://github.com/polkadot-js/extension).
