### ISSUE TITLE
loan交易失败

### ISSUE THREAD

**Issue by hijonehi** [AcalaNetwork/acala-dapp#26]
在进行loan交易时，失败频率较高，而且也不显示原因，也没有记录Tx Hash

DOT | Deposit 0.2 DOT, Generate 52 aUSD | 2020/03/06 20:55
-- | -- | --

5G8jj92pf4yG9cQmQ6mbRUqBePMptB37b7GGBg8FMoDKL9Gv

**Comment by qwer951123** [comment]
交易失败且并没有记录 hash ，可能是由于与节点的连接中断导致交易并没有发送到链上。

**Comment by qwer951123** [comment]
track this issue at #24 and this will be closed.
