### ISSUE TITLE
The ticker and symbol of previous self-serviced loan persists.

### ISSUE THREAD

**Issue by ilhanu** [AcalaNetwork/acala-dapp#273]
A small UI bug, could also be browser related, not sure, but it's good to know.

I had just paid of my DOT self-serviced loan and went to the XBTC screen to also withdraw and/or deposit some collateral. The browser still shows the DOT logo, when I'm on the XBTC loan. The information regarding the collateral and borrowed are all correct per token, it's just the UI not swapping quick enough. 

XBTC Loan, shows DOT logo
![Screenshot from 2020-10-31 10-18-25](https://user-images.githubusercontent.com/29432367/97775765-8c085280-1b63-11eb-8694-573e5f12560d.png)

DOT Loan, shows XBTC logo
![Screenshot from 2020-10-31 10-21-58](https://user-images.githubusercontent.com/29432367/97775788-ab9f7b00-1b63-11eb-80f1-9b1b388ef076.png)

**What is good to mention:**
1. Currently my internet connection is not the best where I am right now, this might be the cause.
2. Small UI bug that might lead to confusion, but the underlying data per token is correct.

**What is expected:**

To see the corresponding token logo based on the loan the user is active on

**My Acala address:**

5HpLku5nX1Qqr2jUHDXH7rMBB5UVD7gJubNzVijvg6JhJJ9Q

**Comment by StrawberryFlavor** [comment]
This bug has been verified
