### ISSUE TITLE
Governanace page title UI is not standardized

### ISSUE THREAD

**Issue by atinst** [AcalaNetwork/acala-dapp#274]
![120](https://user-images.githubusercontent.com/32417799/97779100-e7176500-1bb6-11eb-9b9c-126ae1d1e58e.png)
As you can see, there are some problems
Acala address：5HnJRCcbFaTjaYhmhTiNavSStkxRAmeX2EiEJq2vSnN5Q4TJ

**Comment by StrawberryFlavor** [comment]
This function has no effect temporarily，you don’t need to pay attention to it
