### ISSUE TITLE
交易完成后，没有交易记录

### ISSUE THREAD

**Issue by yidianshui** [AcalaNetwork/acala-dapp#276]
在各个板块交易完成后，没有交易记录，希望加入交易记录
![mmexport1604154928433](https://user-images.githubusercontent.com/36132527/97781945-a37a2680-1bc9-11eb-8039-b53882e2433d.jpg)

**Comment by StrawberryFlavor** [comment]
Transaction records are provided by Subscan. TC5 has not been upgraded yet. It will take some time, but it will be supported soon
