### ISSUE TITLE
LDOT redeem切换选项后，Received等字段未进行重新计算

### ISSUE THREAD

**Issue by Kavelaa** [AcalaNetwork/acala-dapp#277]
### 位置：Liquid DOT菜单 - Advanced子菜单 - Redeem模块

当我选择`Redeem Now`选项，输入要redeem的LDOT的数量之后，`Received`展示了我将收到的dot，以及手续费用`ClaimFee`

![image](https://user-images.githubusercontent.com/37141924/97783731-97479680-1bd4-11eb-9750-e4d3ba4965e9.png)
---
但当我不改变输入框的值，直接切换到另一个选项`Redeem & Wait for Unbounding Period`时，`Received`的值却没有变化

![image](https://user-images.githubusercontent.com/37141924/97783705-7d0db880-1bd4-11eb-85bc-0f44f4608e4d.png)
---
当我将输入框清空，重新输入值之后，上述的字段才发生了更新

![image](https://user-images.githubusercontent.com/37141924/97783759-bb0adc80-1bd4-11eb-8fda-e9181d38d975.png)

看起来像是前端联动的逻辑出现了遗漏

### 我的Mandala Address：5HdRwpyhpLNMiFRtEFL7JyhvkSLNSJGVDnQ1GcnVgTQr5smP

**Comment by StrawberryFlavor** [comment]
This issue has been verified
