### ISSUE TITLE
acala app异常退出

### ISSUE THREAD

**Issue by davidzj0718** [AcalaNetwork/acala-dapp#280]
![acala-error01](https://user-images.githubusercontent.com/52592290/97795221-9ba89980-1c3e-11eb-9b1b-d32825a6566e.jpg)

重新刷新，都没有用。

地址：
5DPktSRKZrZUz3UeaM57aukqDa6SJQXTsmQcbnf8dpNFqEKT

**Comment by StrawberryFlavor** [comment]
#281 Same reason
