### ISSUE TITLE
DOT-aUSD Action 界面直接死掉

### ISSUE THREAD

**Issue by davidzj0718** [AcalaNetwork/acala-dapp#281]
![acala-error02](https://user-images.githubusercontent.com/52592290/97795357-26d65f00-1c40-11eb-9a8a-411a780a3388.jpg)

选择max操作，页面一直在刷新，整个界面有无法操作。只有重新关闭页面。

地址：
5HHECGnb51XLhPzWWUqumWxb9KwTARmcunxMXvkyNCqRqDX3

**Comment by StrawberryFlavor** [comment]
This issue has been verified
