### ISSUE TITLE
AMM模块，超额存入流动性没有提示

### ISSUE THREAD

**Issue by hijonehi** [AcalaNetwork/acala-dapp#282]
在存入流动性时，aUSD已达账户最大余额，但是DOT仍可输入超过限定的数额，而且aUSD没有提示余额不足。点deposit按钮也可以正常启动交易。

![image](https://user-images.githubusercontent.com/61875854/97808252-c9262f00-1ca0-11eb-892c-04f9a509f99b.png)

![image](https://user-images.githubusercontent.com/61875854/97808347-62554580-1ca1-11eb-894a-b3b64712a4a6.png)

5HnB6WGwGFZU87ViXYhVxxPEKS1K8r2QTQnvSPg9tWqVApxY

**Comment by StrawberryFlavor** [comment]
This issue has been verified
