### ISSUE TITLE
浏览器和钱包显示ACA余额不一致

### ISSUE THREAD

**Issue by jiangzhanwei** [AcalaNetwork/acala-dapp#285]
![image](https://user-images.githubusercontent.com/19163404/97837226-c109d600-1d18-11eb-881b-54e53fa28b84.png)
![image](https://user-images.githubusercontent.com/19163404/97837274-d4b53c80-1d18-11eb-92ed-f7922132756b.png)

ACA地址
5FEp7o7MW6m5Tx6G5pGeto9ZQpfHKePVREVkmDxV58ZoPg6H

**Comment by StrawberryFlavor** [comment]
这是由于波卡钱包中将开户费也显示了，实际上web端保留了一个开户费，如果被使用掉将会销户，为了避免就将其去掉了
