### ISSUE TITLE
Swap max balance don't work

### ISSUE THREAD

**Issue by Madbustazz** [AcalaNetwork/acala-dapp#286]
Hi! I trying swap max balance my ACA to DOT but app don't conform it, If i reduce ACA coin all good. See video.
My address: 5CADxhweP2DLG1zvdVbUmf9ECPDW8nEETHz32E9E4wBLpxoJ
https://www.dropbox.com/s/ffh6itp4hx6befu/2020-11-02_15-45-36.mp4?dl=0

**Comment by StrawberryFlavor** [comment]
Because the fee is paid by ACA, you cannot use all ACA to swap, Please reserve a little ACA balance
