### ISSUE TITLE
No transaction history on Liquid dot

### ISSUE THREAD

**Issue by Madbustazz** [AcalaNetwork/acala-dapp#287]
Hi! I test Liquid dot, stake and unstake works good but in transaction history clear see video.
My address: 5CADxhweP2DLG1zvdVbUmf9ECPDW8nEETHz32E9E4wBLpxoJ
https://www.dropbox.com/s/xzfc1i0fj0xuap7/2020-11-02_15-59-00.mp4?dl=0

**Comment by StrawberryFlavor** [comment]
Transaction records are provided by Subscan. TC5 has not been upgraded yet. It will take some time, but it will be supported soon
