### ISSUE TITLE
I can't claim reward for pool ACA-aUSD

### ISSUE THREAD

**Issue by Madbustazz** [AcalaNetwork/acala-dapp#288]
Hi! I can't claim reward for pool ACA-aUSD
![2020-11-02_16-17-05](https://user-images.githubusercontent.com/53031434/97862222-c79f4a00-1d26-11eb-8f97-726c572171ce.png)
![2020-11-02_16-17-44](https://user-images.githubusercontent.com/53031434/97862228-ca01a400-1d26-11eb-9817-4f517153c9c7.png)
I dont't see claim button

My address: 5CADxhweP2DLG1zvdVbUmf9ECPDW8nEETHz32E9E4wBLpxoJ

**Comment by StrawberryFlavor** [comment]
After increasing liquidity in AMM, manual pledge is required
