### ISSUE TITLE
bug in pool renbtc-ausd

### ISSUE THREAD

**Issue by Madbustazz** [AcalaNetwork/acala-dapp#290]
Hi! I have bug see video
https://www.dropbox.com/s/psjt5z29hijfgx7/2020-11-02_16-30-43.mp4?dl=0
After https://apps.acala.network/ do not respond! Help only reboot
My address: 5CADxhweP2DLG1zvdVbUmf9ECPDW8nEETHz32E9E4wBLpxoJ

**Comment by Madbustazz** [comment]
https://www.dropbox.com/s/3bt1pja456j1qjb/2020-11-02_16-39-42.mp4?dl=0

**Comment by Madbustazz** [comment]
step by step from another account:
![2020-11-02_16-56-56](https://user-images.githubusercontent.com/53031434/97865668-624e5780-1d2c-11eb-8339-03f96da9233c.png)
![2020-11-02_16-57-49](https://user-images.githubusercontent.com/53031434/97865678-64b0b180-1d2c-11eb-86fb-69fbb45d87ad.png)
![2020-11-02_16-58-06](https://user-images.githubusercontent.com/53031434/97865687-68443880-1d2c-11eb-8bee-c7a2543988dc.png)
![2020-11-02_16-58-30](https://user-images.githubusercontent.com/53031434/97865774-8b6ee800-1d2c-11eb-8280-9d1e2d21c8f2.png)
https://www.dropbox.com/s/uusywnelkmyiz37/2020-11-02_17-01-12.mp4?dl=0

**Comment by StrawberryFlavor** [comment]
#281 The same reason，All are web errors caused by the MAX button
