### ISSUE TITLE
【Liquid DOT】 No response when clicking on the 'MAX' icon

### ISSUE THREAD

**Issue by wiki-wang** [AcalaNetwork/acala-dapp#294]
1. go to Liquid DOT.
2. go to Unstake
3. click the 'MAX' icon
![image](https://user-images.githubusercontent.com/45313086/97795167-da8a1f80-1c3d-11eb-8596-c4a9e7990921.png)
4. it is not response.

My Acala Mandala address is 5CUpyz4irvybSgdZpuPJAFi2ApDqzp8QtfUgR7vWtagFcHGn .

**Comment by StrawberryFlavor** [comment]
#292 The same reason

**Comment by StrawberryFlavor** [comment]
It seems that you submitted the issue to the wrong warehouse. I checked the time. In fact, you submitted it earlier, but you did not submit it to the correct place. Even so, thank you for your contribution and will mark it for you.  Next time please submit directly to https://github.com/AcalaNetwork/acala-dapp/issues
