### ISSUE TITLE
LP Reward没有正确显示我的Rate

### ISSUE THREAD

**Issue by Kavelaa** [AcalaNetwork/acala-dapp#296]
### 位置：Earn主菜单 - LP Reward子菜单
可以看到，我在AMM主菜单中，给ACA-aUSD池提供了0.18个点的流动性

![image](https://user-images.githubusercontent.com/37141924/97995308-509aac00-1e21-11eb-9846-22cd3868b3ab.png)

但是，在Earn主菜单，LP Reward子菜单的ACA-aUSD模块显示我的Rate为0，根据Pool Rate 1200 ACA / h 计算，我应该有12*0.18 ACA的小时收益。

![image](https://user-images.githubusercontent.com/37141924/97995701-d4549880-1e21-11eb-9b7e-459f14d442a1.png)

### 我的Mandala地址：5HdRwpyhpLNMiFRtEFL7JyhvkSLNSJGVDnQ1GcnVgTQr5smP

**Comment by StrawberryFlavor** [comment]
#291
