### ISSUE TITLE
I can mint renBTC when my deposit is null

### ISSUE THREAD

**Issue by apastushenko** [AcalaNetwork/acala-dapp#297]
Sum of deposit  = 0
![image](https://user-images.githubusercontent.com/9716308/98014569-79f90f00-1e04-11eb-8f5e-baf9e2c9051d.png)

Acala Mandala Address - 5Gea8NyheFoTbXM53Uwgh9WMQ9hJPURiLdUdgNW4Acf5L8rH

**Comment by StrawberryFlavor** [comment]
This is temporarily a short position similar to a faucet and can receive RENBTC
