### ISSUE TITLE
loan交易成功，但是没有Tx Hash

### ISSUE THREAD

**Issue by hijonehi** [AcalaNetwork/acala-dapp#30]
在loan界面进行dot的借贷操作，输入密码后一直转圈，最后刷新页面重新进入后发现交易成功了，但是没有Tx Hash。

![image](https://user-images.githubusercontent.com/61875854/76145798-0f9e9c00-60c8-11ea-8b0d-36dd9d2cbec4.png)

5G8jj92pf4yG9cQmQ6mbRUqBePMptB37b7GGBg8FMoDKL9Gv

**Comment by qwer951123** [comment]
可能是网络问题，没有收到交易成功/失败的消息，导致页面一直锁住，由于 tx hash 是在交易成功后读取的，所以没有读取到 tx hash。这个问题我们将会尽快解决。

**Comment by qwer951123** [comment]
track this issue at #24 and this will be closed.
