### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by apastushenko** [AcalaNetwork/acala-dapp#307]
![image](https://user-images.githubusercontent.com/9716308/98120446-a1101900-1eb6-11eb-92ff-78b4709f3b5f.png)

Acala Mandala Address - 5Gea8NyheFoTbXM53Uwgh9WMQ9hJPURiLdUdgNW4Acf5L8rH

**Comment by StrawberryFlavor** [comment]
#303 The same reason
