### ISSUE TITLE
After swapping, the "insufficient balance" message keeps coming

### ISSUE THREAD

**Issue by togamamora** [AcalaNetwork/acala-dapp#309]
SWAP
The "insufficient balance" keep on popping after swapping whatever to whatever regardless if there is a balance.

![Bug1](https://user-images.githubusercontent.com/37278708/98207504-bc425d80-1f76-11eb-8558-91c60e5b80ac.JPG)

Wallet Address: 5EsnfdJhmf8XFkWfLhJY23TcMLi6KyvE6XBsGNyhGtccdcJ8

**Comment by StrawberryFlavor** [comment]
The types of problems you mentioned are all caused by previous MAX bugs.  Since we are currently debugging, there will be some such problems, please wait for updates
