### ISSUE TITLE
"Greater than the max amount 0" pop up message

### ISSUE THREAD

**Issue by togamamora** [AcalaNetwork/acala-dapp#310]
1. Self serviced loan - manage loan - deposit/withdraw (collateral) - max

The "greater than the max amount 0" pop up message appears.  Sometimes it appears after signing the transaction, sometimes before signing the transaction. It only happens when "max" is selected.

![Bug2](https://user-images.githubusercontent.com/37278708/98208933-1512f580-1f79-11eb-9a10-99e0597e9c1e.JPG)
![Bug2a](https://user-images.githubusercontent.com/37278708/98208938-16dcb900-1f79-11eb-881d-33f92ec063f8.JPG)

2. This also happens when:
Self serviced loan - manage loan - payback (borrowed) - max
![Bug2b](https://user-images.githubusercontent.com/37278708/98209417-d3cf1580-1f79-11eb-8049-83e7da41e22e.jpg)

The message is not supposed to be there because there is not error on the amount.

3. The message also appears when:
Self serviced loan - manage loan - generate (borrowed) - value entered is more than max.
But this is ok, since the error is legit.
![Bug2c](https://user-images.githubusercontent.com/37278708/98210850-32958e80-1f7c-11eb-9538-eff54b94682c.JPG)

My wallet:
5EsnfdJhmf8XFkWfLhJY23TcMLi6KyvE6XBsGNyhGtccdcJ8

**Comment by StrawberryFlavor** [comment]
The same problem causes
