### ISSUE TITLE
Add "MAX" button on Generate Borrow

### ISSUE THREAD

**Issue by togamamora** [AcalaNetwork/acala-dapp#311]
Self serviced loan - manage loan - generate

Adding a "max" button would ease and fasten the process, instead of typing manually.

![Bug3](https://user-images.githubusercontent.com/37278708/98212654-e009a180-1f7e-11eb-833e-0989fc01565d.JPG)

My wallet:
5EsnfdJhmf8XFkWfLhJY23TcMLi6KyvE6XBsGNyhGtccdcJ8

**Comment by StrawberryFlavor** [comment]
The demand is unreasonable. In fact, the larger the borrow, the higher the risk, and there is liquidation risk
