### ISSUE TITLE
"Insufficient Balance" pop up message right after swapping max

### ISSUE THREAD

**Issue by togamamora** [AcalaNetwork/acala-dapp#312]
Swap - select any pair - swap max

The insufficient balance appears right after swapping is done. This pop up message shouldn't have been here.  It is not logical to tell people that the balance is insufficient when they have just done swapping.
![Bug4](https://user-images.githubusercontent.com/37278708/98213499-1c89cd00-1f80-11eb-8a31-3e034fe8eeb9.jpg)

However, the pop up message do appear correctly when I do not have any balance yet I enter a number.

![Bug4a](https://user-images.githubusercontent.com/37278708/98213649-58249700-1f80-11eb-9267-3005dac3e407.JPG)

My wallet:
5EsnfdJhmf8XFkWfLhJY23TcMLi6KyvE6XBsGNyhGtccdcJ8

**Comment by StrawberryFlavor** [comment]
The same problem causes
