### ISSUE TITLE
Add "max" button in borrow box

### ISSUE THREAD

**Issue by togamamora** [AcalaNetwork/acala-dapp#313]
Self serviced loan - create - select any coin - "max"
![Bug5](https://user-images.githubusercontent.com/37278708/98214441-78088a80-1f81-11eb-9b9a-78c2eb58d0cc.JPG)

This would simplify/fasten the process instead of typing manually.

My wallet:
5EsnfdJhmf8XFkWfLhJY23TcMLi6KyvE6XBsGNyhGtccdcJ8

**Comment by StrawberryFlavor** [comment]
The demand is unreasonable. In fact, the larger the borrow, the higher the risk, and there is liquidation risk
