### ISSUE TITLE
"Token Balance Too Low" Error Message

### ISSUE THREAD

**Issue by togamamora** [AcalaNetwork/acala-dapp#314]
1. Self serviced loan - manage loan - payback - max

While I have 10,000 aUSD and wanting to payback max 10,000 aUSD, the error message "token balance too low" appeared on the top right after confirming and signing the transaction.
![Bug6](https://user-images.githubusercontent.com/37278708/98215754-27922c80-1f83-11eb-8c40-64aae9adafc2.JPG)

After confirming. Hence I can't payback max amount.
![Bug6a](https://user-images.githubusercontent.com/37278708/98215759-295bf000-1f83-11eb-96e6-6f6865e01c2c.jpg)

What is the issue that I can't pay back max?

My wallet:
5EsnfdJhmf8XFkWfLhJY23TcMLi6KyvE6XBsGNyhGtccdcJ8

**Comment by StrawberryFlavor** [comment]
The debt to be repaid is actually more than this, because the block has been going on, and your balance is already insufficient
