### ISSUE TITLE
Liquid DOT模块下的unstake界面显示有错误

### ISSUE THREAD

**Issue by nantianhaike** [AcalaNetwork/acala-dapp#316]
![1](https://user-images.githubusercontent.com/35984173/98320077-1695f980-201d-11eb-990d-60ae51d8692a.jpg)
![2](https://user-images.githubusercontent.com/35984173/98320090-1e559e00-201d-11eb-8418-0d763825c0f1.jpg)
在Liquid 进行 unstake 操作时，一开始点击进去界面显示正常，上面是LDOT ，下面一列是DOT，但是在LDOT一栏输入数字的时候，下面的DOT显示变成了LDOT，明显是错误的。
Acala Mandala Address ：
5CB6bxLb9jDna7tAeJMAMRaFDsSjRhiEvwFJJpRDCLXBE55o

**Comment by StrawberryFlavor** [comment]
It has been fixed
