### ISSUE TITLE
Loan -> Can Generate aUSD amount has 1 significant figure (1 decimal place) for cents value

### ISSUE THREAD

**Issue by imylomylo** [AcalaNetwork/acala-dapp#39]
Acala Mandala Account: `5F52pY196ZVifs3xGvBK5RTFuWMLsxNPrTfTTfk7NHC4YrS7`

Loan section of app, available amount available to generate displays $66.8 instead of $66.80, reducing the significant figures for dollar value.

![acala-loan-can-generate-rounding-1dp](https://user-images.githubusercontent.com/19399102/76295077-e9395600-62ab-11ea-8cbe-fa5196134328.png)

Impact: Some users may end up confused if USD is not their currency, maybe thinking 66 dollars and 8 cents instead of 66 dollars and 80 cents.  To correct their own mistake, they'll generate another tx increasing tx space, bandwidth etc. for node operators.

**Comment by jiangfuyao** [comment]
@imylomylo Already rewarded.
