### ISSUE TITLE
A script errors

### ISSUE THREAD

**Issue by lijiahao666** [AcalaNetwork/acala-dapp#57]
![1589101366290](https://user-images.githubusercontent.com/57653984/81495076-3c5f6300-9273-11ea-83b3-29853d32a1b6.jpg)
I found some ACA in my wallet，but I didn't get any ACA（mainnet）.I think it is a script error results. If this script error is not resolved. The project will lose a lot of ACA after the main network is launched.
5CG4jmkk1neZzbKCeQg7kYv9PMko8zkcRqVvAFzPHuBD673q

**Comment by qwer951123** [comment]
already fixed.
