### ISSUE TITLE
On the "D&E" tab amount is not calculated when entering amount of 2nd currency

### ISSUE THREAD

**Issue by illlefr4u** [AcalaNetwork/acala-dapp#59]
On the "Deposit & Earn" tab, when entering the amount of second currency, the amount of the first is not calculated.

gif with explanation is attached:
![acala_ui2](https://user-images.githubusercontent.com/21253681/81515210-4df34a00-9309-11ea-98ca-73adc9d12829.gif)

My Acala Mandala Account: 5CJX5TSEokNNvgN23BKDLg5wPrC1hjmNb99hwndgEJK5x5jK

**Comment by qwer951123** [comment]
Thanks for your feedback. The second input doesn't calculate is for user input manually but on the other hand, auto calculate could save your time if he decides the deposit amount by ausd. we will add this feature.
