### ISSUE TITLE
On the "Swap" tab amont of 1st currency is cleared when 2nd currency changes

### ISSUE THREAD

**Issue by illlefr4u** [AcalaNetwork/acala-dapp#60]
On "Swap" tab amont of first currency is cleared when second currency changes.
Also, the amount are not transferred (cleared) when reversing exchanged currencies.

gif with explanation is attached:
![acala_ui4](https://user-images.githubusercontent.com/21253681/81515871-5ef18a80-930c-11ea-8f01-2b3f3982ff3e.gif)

My Acala Mandala Account: 5CJX5TSEokNNvgN23BKDLg5wPrC1hjmNb99hwndgEJK5x5jK

**Comment by qwer951123** [comment]
Thanks for your feedback,  we will improve the users' experience.
