### ISSUE TITLE
On the "Swap" tab need to add available amount of selected currency

### ISSUE THREAD

**Issue by illlefr4u** [AcalaNetwork/acala-dapp#61]
For the better user experience on the "Swap" tab, it is necessary to add the number of selected currencies available on the wallet, since this is very inconvenient to go every time to wallet tab  to understand how much you can/need to exchange.

![acala_ui5](https://user-images.githubusercontent.com/21253681/81516096-30c07a80-930d-11ea-8f96-c578af8e8e6c.png)

My Acala Mandala Account: 5CJX5TSEokNNvgN23BKDLg5wPrC1hjmNb99hwndgEJK5x5jK

**Comment by qwer951123** [comment]
Thanks for your feedback, we will improve the user express in some way.
