### ISSUE TITLE
钱包弹窗Bug

### ISSUE THREAD

**Issue by zy4l1** [AcalaNetwork/acala-dapp#65]
![image](https://user-images.githubusercontent.com/62460007/81522384-f262a400-937c-11ea-9c39-28570fd79f26.png)
我有多个波卡钱包地址(一页放不下),波卡钱包插件弹窗选择钱包的时候,无法向下滚动,所以confirm按钮不显示,从而选择不了钱包,无法操作.我F12调试了一下发现,钱包插件弹窗没有设置最大高度.我给弹窗加了这两个属性就正常了:height: -webkit-fill-available;
    overflow-y: scroll

5GBM5hNhzHerACkb5aFvK1X4T4CMmBSAVxSGmtsLFp7iPtky

**Comment by qwer951123** [comment]
already fixed.
