### ISSUE TITLE
 Incorrectly calculates the aUSD / LDOT rate

### ISSUE THREAD

**Issue by randlmac** [AcalaNetwork/acala-dapp#66]
On the swap tab incorrectly calculates the aUSD / LDOT rate
![ACALA BUG1](https://user-images.githubusercontent.com/55245481/81522572-b109ce80-9353-11ea-8a89-cb59f97d9a23.png)

My Acala Mandala Account: 5DCdUUZSEsdB3JBwdyQsKjEwdjWLyVajJaeki66M5YhGYWyK

**Comment by randlmac** [comment]
and other pairs / LDOT - the same problem

**Comment by qwer951123** [comment]
The calculate is correct and the formula is (current DOT * current aUSD) =  (new DOT * new USD). the exchange rate is estimated, only according to the current pool size. 
when the pay/receive amount is too much, the exchange rate will appear a big slippage.
