### ISSUE TITLE
Transaction history issue

### ISSUE THREAD

**Issue by xz-cn** [AcalaNetwork/acala-dapp#68]
Transactions performed using `https://console.acala.network/` are not shown in the transaction history of the Acala apps (`http://apps.acala.networ`). This may lead to inconsistent transaction record for users using different interface. 

5G3zwZ72e6rbJgx6cfmpKac3yBPsLM1hC173U6XNeMexqMhS

**Comment by qwer951123** [comment]
thanks for your feedback, acala apps's transaction history is saved in local now, update this component is in our todo list.

**Comment by qwer951123** [comment]
track this issue at #24 and this will be closed.
