### ISSUE TITLE
Self Serviced Loan bug

### ISSUE THREAD

**Issue by zhangshuai5688** [AcalaNetwork/acala-dapp#69]
Deposit LDOT as collateral to genearte AUSD,Unable to exchange normally。Other currencies can be freely traded
![微信图片_20200511184813](https://user-images.githubusercontent.com/39653400/81553628-04ae0380-93b8-11ea-8f1a-fceebcf94f75.png)
5ERFkyHHuuSvgKYLuPi5a6M21nmjNetF9ebwBD8j8ougSqJZ

**Comment by qwer951123** [comment]
already fixed.
