### ISSUE TITLE
Self Serviced Loan is not working for LDOT 

### ISSUE THREAD

**Issue by ujgeeck** [AcalaNetwork/acala-dapp#70]
When I enter deposit amount of LDOT,in below section "maximun to borrow" aUSD is not calculated and when i manually enter aUSD amount, cant click on 'Next' buton,button remains disabled. Kindly solve it. This function working for DOT and XBTC. attachingin gif for better explaination; 
![issue#1](https://user-images.githubusercontent.com/65138658/81560018-34f0a480-93ae-11ea-9c59-71287e96583c.gif)

5FsiEWzjVYihbiRNw11Mmrii8Y7HpZ9wvPs82Z5Gzidvpqey

**Comment by qwer951123** [comment]
same as #69 and already fixed

**Comment by ujgeeck** [comment]
> same as #69 and already fixed

Sorry. butnot working yet

**Comment by qwer951123** [comment]
> > same as #69 and already fixed
> 
> Sorry. butnot working yet

Is it working now? Mine is working , Maybe you should reload the page?

**Comment by qwer951123** [comment]
already fixed
