### ISSUE TITLE
unable to generate aUSD for LDOTs

### ISSUE THREAD

**Issue by ujgeeck** [AcalaNetwork/acala-dapp#71]
I can deposit and withdraw LDOTs but cannot generate aUSD. function is not working.
Acala Mandala account:  5FsiEWzjVYihbiRNw11Mmrii8Y7HpZ9wvPs82Z5Gzidvpqey
![2020-05-11 17 53 57](https://user-images.githubusercontent.com/65138658/81561334-ad586500-93b0-11ea-9bf1-39e70708d13b.jpg)

**Comment by qwer951123** [comment]
Thanks for your feedback, the reason is the same as  #69 ,a  bug caused the LDOT price is 0 sometimes, so the user can't do anything to LDOT, and this is fixed now.

**Comment by qwer951123** [comment]
already fixed
