### ISSUE TITLE
Add 'max' button in Deposit & Earn tab

### ISSUE THREAD

**Issue by ujgeeck** [AcalaNetwork/acala-dapp#72]
If there is 'max' button near the asset name it will be convenient for the users.
My Acala Mandala account: 5FsiEWzjVYihbiRNw11Mmrii8Y7HpZ9wvPs82Z5Gzidvpqey

![2020-05-11 18 27 00](https://user-images.githubusercontent.com/65138658/81565133-7d13c500-93b6-11ea-9834-3b9a6b77021f.jpg)

**Comment by wangjj9219** [comment]
good suggestion
