### ISSUE TITLE
Self Serviced Loan交易失败，但是提示成功

### ISSUE THREAD

**Issue by olddaddy2020** [AcalaNetwork/acala-dapp#73]
在Self Serviced Loan中用Ldot抵押借款，交易失败，但是交易完成后弹出的对话框却提示交易成功

![图片](https://user-images.githubusercontent.com/61872737/81583115-7485b380-93e3-11ea-9b87-78f2df274662.png)

![图片](https://user-images.githubusercontent.com/61872737/81582915-2ec8eb00-93e3-11ea-8509-1eb4a74b10c2.png)

5Cqf1u9Dzz1yYKTnFMKRmCX49eSzhq1QgoagpMqWzBEKgz8u

**Comment by qwer951123** [comment]
Thanks for your contribution, The success means the extrinsic is inblock,  we should update tx notification display.
