### ISSUE TITLE
Functions of swap in Acala Mandala 

### ISSUE THREAD

**Issue by MarininM** [AcalaNetwork/acala-dapp#74]
[https://apps.acala.network/swap](url)
![unnamed (2)](https://user-images.githubusercontent.com/65186627/81606684-2c16c780-93dc-11ea-9280-7d344a866a45.jpg)
BLUE - total bitcoins ( BTC)
RED - total Acala (ACA)
GRAY - fiat dollar at the moment (USD)
PINK - automatic determination of the amount when choosing a different currency 
PINK for GREEN - automatic determination of the selected currency

5FF7F1eDV59gH1yzamUuhzWkjwf96gZDWDK7tCUDehDuKfQk

**Comment by illlefr4u** [comment]
the same as #61

**Comment by MarininM** [comment]
cool that you notice the resemblance
it means that for sure developers should pay attention to this and my proposal is more voluminous and functional

**Comment by qwer951123** [comment]
track this issue at #61 and this will be closed.
