### ISSUE TITLE
Deposit & Earn https://apps.acala.network/deposit

### ISSUE THREAD

**Issue by MarininM** [AcalaNetwork/acala-dapp#75]
it would be great if we click on the bunker and would automatically see the Deposit
![IMG_7771](https://user-images.githubusercontent.com/65186627/81619935-54f68700-93f3-11ea-95db-c7bed225ee6c.jpg) https://acala.network/  
![0_jtrfXlllLsc1QIgG](https://user-images.githubusercontent.com/65186627/81620852-81ab9e00-93f5-11ea-8cb6-4ab6b558abb7.jpeg)
function of quick detection needed for quick follow-up.
Please, look at this and we will get a good product in it!
https://apps.acala.network/deposit CANDY_UI_BUG 

5FF7F1eDV59gH1yzamUuhzWkjwf96gZDWDK7tCUDehDuKfQk

**Comment by wangjj9219** [comment]
thx, similar to #72

**Comment by qwer951123** [comment]
track this issue at #72 and this will be closed.
