### ISSUE TITLE
On "Swap" tab "max" button is necessary

### ISSUE THREAD

**Issue by randlmac** [AcalaNetwork/acala-dapp#76]
On "Swap" tab "max" button is absolutely necessary for the convenience of users because Wallet Balance requires page scrolling.
My Acala Mandala account: 5DCdUUZSEsdB3JBwdyQsKjEwdjWLyVajJaeki66M5YhGYWyK 
![ACALA BUG2](https://user-images.githubusercontent.com/55245481/81634878-83d32400-9418-11ea-83fb-f9aac4d47f4b.png)

**Comment by qwer951123** [comment]
Thanks for your feedback, we will improve the user express in some way.

**Comment by qwer951123** [comment]
and this is same as #61

**Comment by qwer951123** [comment]
track this issue at #61 and this will be closed.
