### ISSUE TITLE
Swap页面行宽超出

### ISSUE THREAD

**Issue by sun1534** [AcalaNetwork/acala-dapp#77]
![image](https://user-images.githubusercontent.com/4899200/81635431-ce1dca80-9443-11ea-9768-ec95d4906701.png)

**Comment by jiangfuyao** [comment]
@sun1534 Add the Acala Mandala address, thanks.

**Comment by sun1534** [comment]
> @sun1534 Add the Acala Mandala address, thanks.

5DLXtwVzabzHAAjwbHC1eisdHWsKCEcpovfHiuUQZpSUWBi6

**Comment by qwer951123** [comment]
already fixed.
