### ISSUE TITLE
Balances and Cancelation of Deposits

### ISSUE THREAD

**Issue by Vcryptor** [AcalaNetwork/acala-dapp#79]
The balance is being updated very slowly, it takes up to 10 seconds. Plus, after the canceling of the deposit, the deposit button stays in the pending mode and the only way to start using it again is to reload the page. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/62481941/81649673-59de2980-9439-11ea-9ab7-b2379e8084fa.gif)

Acala address: 5GWj7uVdbEhTad1SwTyqaD2W7h1jX3fMSaWweHR3M3KHj9Qs

**Comment by qwer951123** [comment]
Thanks for your contribution,  We will fix it.

**Comment by Vcryptor** [comment]
Thank you for your efforts to create decentralized future on Polkadot)
