### ISSUE TITLE
swap时，LDOT兑aUSD汇率错误

### ISSUE THREAD

**Issue by olddaddy2020** [AcalaNetwork/acala-dapp#80]
在swap中，LDOT兑aUSD汇率错误，10LDOT竟然兑换 2876.050057 aUSD（当时实际汇率是42.002644）
Tx Hash：0x445bbf62d44556204bdcd54ec603ff9255585d869e4c09c7649063a6915e3e7d

![图片](https://user-images.githubusercontent.com/61872737/81662159-bfe5a380-946f-11ea-8967-223ff3bd945b.png)

![图片](https://user-images.githubusercontent.com/61872737/81662212-d3910a00-946f-11ea-89e4-67f8bf6a1451.png)

5GZ3Yna3Wa3cfoFHt7eakpzZUj2QVxGEMmXbGyux8BnEVCRr

**Comment by wangjj9219** [comment]
汇率计算那里应该存在问题， 导致交易失败https://acala-testnet.subscan.io/extrinsic/0x445bbf62d44556204bdcd54ec603ff9255585d869e4c09c7649063a6915e3e7d

我们复现错误后会回复
