### ISSUE TITLE
UI-BUG操作页面右侧的操作按钮显示不全

### ISSUE THREAD

**Issue by Jason1215** [AcalaNetwork/acala-dapp#82]
![image](https://user-images.githubusercontent.com/26864300/81707741-6ac38500-94a3-11ea-8295-af3c4083b0a5.png)

5CGTA6rbmd79s6xfaTVodNUxxGyfPEhAJnJqPg2VvwqFf8ih

**Comment by Jason1215** [comment]
Macbook pro macOS High Sierra10.13.6

**Comment by Jason1215** [comment]
其实不止是右侧按钮显示不全,好几个页面的右侧部分都显示不全,首页也是,只显示这些
![image](https://user-images.githubusercontent.com/26864300/81710133-19b49080-94a5-11ea-849c-c207da491f05.png)

**Comment by qwer951123** [comment]
谢谢反馈，我们将会调整不同分辨率的显示效果，这部分已经在开发计划中。

**Comment by qwer951123** [comment]
same as #77

**Comment by qwer951123** [comment]
already fixed.
