### ISSUE TITLE
"interesting" Liquid -  L-DOT 

### ISSUE THREAD

**Issue by MarininM** [AcalaNetwork/acala-dapp#83]
I looked at the essence of this assignment for a long time.
Why is the number of DOT tokens not automatically visible?
But in this case, the amount of L-DOT is visible...
Why, when I press MAX, I see that I unknown amount of DOT
I seems that I have a lot of why .....
Let's make it more convenient and understandable.
![unnamed (3)](https://user-images.githubusercontent.com/65186627/81734666-86775d00-949c-11ea-8b9b-be63c6311a5c.jpg)

5FF7F1eDV59gH1yzamUuhzWkjwf96gZDWDK7tCUDehDuKfQk

**Comment by qwer951123** [comment]
Probably sometimes the max value is not updated immediately, Thanks for your feedback

**Comment by MarininM** [comment]
I'm use today and it works good.
