### ISSUE TITLE
No Transaction history update in Deposit and earn tab

### ISSUE THREAD

**Issue by ujgeeck** [AcalaNetwork/acala-dapp#84]
I made two orders in deposit and earn tab using ACA , !st time with 3ACA and 2nd time with 1 ACA. And surprisingly there is no update in transaction history panel but when I checked txn on https://acala-testnet.subscan.io/account/5F7GEvuxExYGhrhVs9AZEqL7dLWsdwpNCjcQGBDD8Pm7qoVX
 the both txns were showing. I refreshed the page even restarted the browser but no update.
![2020-05-13 01 32 06](https://user-images.githubusercontent.com/65138658/81741286-f1845c00-94bb-11ea-9cc3-7131480b1fb8.jpg)
![2020-05-13 01 47 43](https://user-images.githubusercontent.com/65138658/81741291-f5b07980-94bb-11ea-8e0d-d8944044df91.jpg)

My ACALA Address- 5F7GEvuxExYGhrhVs9AZEqL7dLWsdwpNCjcQGBDD8Pm7qoVX

**Comment by MarininM** [comment]
it's great that you saw it
I have the same questions for this tab
Cool what you saw it and showed us.

**Comment by ujgeeck** [comment]
> it's great that you saw it
> I have the same questions for this tab
> Cool what you saw it and showed us.

Thanks mate :)

**Comment by wangjj9219** [comment]
At present,  operation record recorded in localstorage, which relies the callbacks for event subscribe，and timeout will result in failure to record.

Subscan will provide data services for mandala testnet,  then operation records will be directly obtained from their data sources when ready

**Comment by qwer951123** [comment]
track this issue at #24 and this will be closed.
