### ISSUE TITLE
当取回LDOT时，输入框输入的是10，但是实际取回的却是最大可以取回的数字

### ISSUE THREAD

**Issue by nantianhaike** [AcalaNetwork/acala-dapp#86]
当取回LDOT时，输入框输入的是10，但是实际取回的却是最大可以取回的数字，也就是输入框输入的数字并没有效果。如下图：
本来打算取回10个LDOT
![image](https://user-images.githubusercontent.com/35984173/81765830-6e88f300-9507-11ea-8a28-a7f92f6e49ea.png)
但是实际取回的却是最大可以取回的LDOT，也就是下图中的39.3
![image](https://user-images.githubusercontent.com/35984173/81765937-a5f79f80-9507-11ea-89cb-ba7ab542ca9e.png)

Acala address：5CB6bxLb9jDna7tAeJMAMRaFDsSjRhiEvwFJJpRDCLXBE55o

**Comment by wangjj9219** [comment]
历史记录的显示bug，thx for reporting

**Comment by qwer951123** [comment]
Thanks for your contribution, This bugs already fixed, Please reload the apps.
