### ISSUE TITLE
PC网站得显示界面右边的部分不能完全显示出来

### ISSUE THREAD

**Issue by nantianhaike** [AcalaNetwork/acala-dapp#87]
右边部分不能完全显示出来，导致有些功能没法操作，如下：
![image](https://user-images.githubusercontent.com/35984173/81767629-78145a00-950b-11ea-8776-718de2277ff3.png)

使用的笔记本显示分辨率如下图所示：
![image](https://user-images.githubusercontent.com/35984173/81767667-8d898400-950b-11ea-91ce-aaa714d965e4.png)

Acala address：5CB6bxLb9jDna7tAeJMAMRaFDsSjRhiEvwFJJpRDCLXBE55o

**Comment by qwer951123** [comment]
谢谢反馈，我们将会调整不同分辨率的显示效果，这部分已经在开发计划中。

**Comment by qwer951123** [comment]
same as #77

**Comment by qwer951123** [comment]
already fixed.
