### ISSUE TITLE
从其它账号转账过来的DOT，无法通过铸造生成LDOT

### ISSUE THREAD

**Issue by nantianhaike** [AcalaNetwork/acala-dapp#88]
如图一，从其它账号转账过来2个DOT
![image](https://user-images.githubusercontent.com/35984173/81768092-bb22fd00-950c-11ea-93da-dd3e312d6943.png)

用DOT铸造LDOT时候，一直无法成功
![image](https://user-images.githubusercontent.com/35984173/81768147-e0177000-950c-11ea-9d87-01ca26d5199b.png)

错误失败的界面如下：
![image](https://user-images.githubusercontent.com/35984173/81768172-ed345f00-950c-11ea-82b2-a3240992b4b1.png)

Acala address：5CB6bxLb9jDna7tAeJMAMRaFDsSjRhiEvwFJJpRDCLXBE55o

**Comment by qwer951123** [comment]
Thanks for your feedback, but I can't reproduce the error, I already do this [here](https://acala-testnet.subscan.io/account/5GgtQMA6hE3h7MUoq5icfjvK95Pgp7oNBku4siTKKbCxRdmu) but succeeded.
