### ISSUE TITLE
Add Wallet Balance Panel in Deposit & Earn Tab

### ISSUE THREAD

**Issue by ujgeeck** [AcalaNetwork/acala-dapp#90]
It will be more handy if there is wallet balance panel added to Deposit & Earn tab (maybe at the upper right corner). Although it shows the balance of selected asset but if it is added user will need not to switch b/w the tabs or change the asset. There is another alternative that is add the horizontal wallet balance bar at the top of all tabs.  
![2020-05-13 18 56 49](https://user-images.githubusercontent.com/65138658/81820567-686a3500-954e-11ea-82b3-86273795fefd.jpg)

My Acala Address- 5FsiEWzjVYihbiRNw11Mmrii8Y7HpZ9wvPs82Z5Gzidvpqey

**Comment by MarininM** [comment]
Good idea!

**Comment by qwer951123** [comment]
Thinks for you suggest, it sounds good. I will forward it to our product design.

**Comment by qwer951123** [comment]
track this issue at #72 and this will be closed.
