### ISSUE TITLE
使用波卡钱包进行操作后，重新登录网址没有Tx Hash记录

### ISSUE THREAD

**Issue by youngwen1987** [AcalaNetwork/acala-dapp#91]
使用波卡钱包进行操作后，重新登录使用谷歌浏览器，不会保留使用钱包操作的记录，网页版的Transaction是空的。

5CojknH9daMVDQ6rZuUSsDjnzDcofvGWRtCsG6y35HJyiDvE

**Comment by qwer951123** [comment]
谢谢反馈，网页版的历史记录是保存在本地的，并不会（也不能）记录 console 和 钱包的操作记录，我们目前正在升级历史记录功能，从而可以查询到全部的真实历史记录。

**Comment by qwer951123** [comment]
track this issue at #24 and this will be closed.
