### ISSUE TITLE
Runtime bugs ----- }}} Swap 

### ISSUE THREAD

**Issue by MarininM** [AcalaNetwork/acala-dapp#92]
![IMG_7796](https://user-images.githubusercontent.com/65186627/81829561-b463ac80-9543-11ea-927c-81b34f491960.jpg)
My balance ACA I show in the photo
I made some operations - see photo 2
![IMG_7789](https://user-images.githubusercontent.com/65186627/81831292-da8a4c00-9545-11ea-8707-4936ca21098f.jpg)
but it’s very strange that deal were successful and commission was debited but transfers werent made
This unacceptable error of using Wallet
I recommend that need to automate this process!
This will be facilitate freedom of use of AcalaMandalaWallet https://apps.acala.network/wallet

5FF7F1eDV59gH1yzamUuhzWkjwf96gZDWDK7tCUDehDuKfQk

**Comment by ujgeeck** [comment]
Faced this also

**Comment by qwer951123** [comment]
Thanks for your feedback, the reason probably is that the tx is submitted successfully, but executed fail, we will update the history component to fetch the history from [subscan](https://acala-testnet.subscan.io/) and show the tx result.

**Comment by MarininM** [comment]
great idea!
