### ISSUE TITLE
Equation text error

### ISSUE THREAD

**Issue by xz-cn** [AcalaNetwork/acala-dapp#93]
![image](https://user-images.githubusercontent.com/46279370/81888756-9abe7580-95d4-11ea-8374-11800cf14703.png)

I think it is the other way around: collateralization ratio =  total collateral in USD / amount borrowed. 

5GCc7JDdXQ8QKnm8itDBd7hbKCKziS8eDrTTFeXmj6HhKTHk

**Comment by qwer951123** [comment]
Thanks for your feedback and you are right, we will fix the description.
