### ISSUE TITLE
 swap XBTC/ LDOT is impossible

### ISSUE THREAD

**Issue by randlmac** [AcalaNetwork/acala-dapp#94]
It does not allow you to swap XBTC/ LDOT
(the button is not active), although there are enough funds(photo1)
![bug3](https://user-images.githubusercontent.com/55245481/81894473-8b313380-95b8-11ea-93c4-6fbef261f049.png)
.Other assets(e.g. aUSD photo 2) in an equivalent amount - swap without any problems.
![bug33](https://user-images.githubusercontent.com/55245481/81894496-97b58c00-95b8-11ea-9af3-83554c940c0f.png)
My Acala Mandala wallet:  5DCdUUZSEsdB3JBwdyQsKjEwdjWLyVajJaeki66M5YhGYWyK

**Comment by qwer951123** [comment]
Thanks for the feedback, This bug is the same as #80, sometimes it gets pool size failed so that calculates an error receive amount.

**Comment by MarininM** [comment]
I also met this error.

**Comment by MarininM** [comment]
I met to this error.
