### ISSUE TITLE
DOT铸造LDOT时，发现LDOT已经铸造出来，但是Transaction里面没有hash记录

### ISSUE THREAD

**Issue by nantianhaike** [AcalaNetwork/acala-dapp#95]
在balance 列表里面显示LDOT已经铸造出来：
![image](https://user-images.githubusercontent.com/35984173/81904712-37ddd600-95f6-11ea-8805-ba177866655d.png)

但是，Transaction里面没有hash记录，如下图：
![image](https://user-images.githubusercontent.com/35984173/81904848-6f4c8280-95f6-11ea-9012-5204fdf46018.png)

My Acala Address：5EEub2a54XhN97vkd41zKzbooqadfatnx5VEmHkvvFP8hj3T

**Comment by qwer951123** [comment]
历史记录组件正在重写，将会取出链上的所有操作记录，用以解决在本地存储所导致的各种问题

**Comment by qwer951123** [comment]
track this issue at #36 and this will be closed.
