### ISSUE TITLE
Transaction result keeps changing itself.

### ISSUE THREAD

**Issue by xz-cn** [AcalaNetwork/acala-dapp#96]
In Self Serviced Loan, if you observe the transaction history, you can see the Generated aUSD numbers in the Action column keep changing. This is strange behavior as a finished transaction should have a fixed Generated aUSD number. 

![acala1](https://user-images.githubusercontent.com/46279370/81914176-8776ce80-9603-11ea-9c17-0c65e4ccdc9d.gif)

5GCc7JDdXQ8QKnm8itDBd7hbKCKziS8eDrTTFeXmj6HhKTHk

**Comment by qwer951123** [comment]
Thanks for your feedback and the Tx history component is redesigning now.

**Comment by qwer951123** [comment]
track this issue at #36 and this will be closed.
