### ISSUE TITLE
No success with Max value when generating aUSD

### ISSUE THREAD

**Issue by xz-cn** [AcalaNetwork/acala-dapp#98]
When I try to generate the maximum amount of aUSD using the max helper button, it never succeeded. I have tried more than ten times and it kept giving the failed indication. This UX right now is not good.

I suspect this is due to the fluctuating price of XBTC. If this is the case, I suggest leave some margin (e.g. only keep two decimal digits) when the user click the max button.

![image](https://user-images.githubusercontent.com/46279370/81913416-872a0380-9602-11ea-8f8c-a909a85cbed2.png)

![image](https://user-images.githubusercontent.com/46279370/81913115-1b479b00-9602-11ea-9082-b6aee0ec3e49.png)

5GCc7JDdXQ8QKnm8itDBd7hbKCKziS8eDrTTFeXmj6HhKTHk

**Comment by qwer951123** [comment]
In my opinion, we can remove this max action button, because generate max debt is a dangerous and unusual action.

**Comment by xz-cn** [comment]
> In my opinion, we can remove this max action button, because generate max debt is a dangerous and unusual action.

Yes, I think this makes sense.

**Comment by qwer951123** [comment]
updated at #111
